import { NodeRunner } from '../../NodeRunner.ts';
import type { TextFile, WhatRuns } from '../../ElementRunner.ts';
import { type Runtime } from '../../Runtime.ts';
import { Logic, logicFrom } from '../../../authoring/logic.ts';
import type { GraphNode } from '../../../graph.ts';
import type { LogicFields } from '../../../authoring/logic.ts';
import type { Generation } from '../../../authoring/generation.ts';

const DATA_FIELDS: LogicFields = {
  body: 'data_format_prompt', prompt: 'data_prompt',
};

export interface DataConfig {
  /** What it holds between runs. */
  value: unknown;
}

/** What this keeps in files of its own in a project folder: see `ElementRunner.texts`. */
const DATA_TEXTS: readonly TextFile[] = [
  { field: 'data_prompt', file: 'task.md' },
  { field: 'data_format_prompt', file: 'format.md' },
];

/**
 * A value that survives a run — the graph's memory.
 *
 * `isMemory` is what lets an edge back into this node close a loop: the
 * executor leaves that edge out of the ordering and settles the fresh value
 * afterwards, so the next round starts from it. A counter is a data node with
 * a code node adding one.
 */
export class DataNodeRunner extends NodeRunner<DataConfig> {
  readonly nodeType = 'data' as const;

  override texts(): readonly TextFile[] {
    return DATA_TEXTS;
  }

  config(node: GraphNode): DataConfig {
    return { value: node.config.data_value ?? '' };
  }

  /**
   * The format contract: written by a person, generated by an AI, and never
   * run. `spec` is the kind for exactly that -- the neighbours' generation
   * prompts read it so their code produces the shape this node holds, but no
   * sandbox ever sees it. Without the third kind it looked like a body someone
   * had forgotten to wire up.
   */
  override logic(node: GraphNode): Logic {
    return logicFrom(node, 'spec', DATA_FIELDS);
  }

  override readonly isMemory = true;

  /** It keeps what it is handed, whether or not the edge closes a loop. */
  override readonly settlesOnArrival = true;

  async execute(node: GraphNode, inputs: Record<string, unknown>, _runtime: Runtime) {
    // An update arriving this round wins; otherwise it emits what it kept.
    const incoming = inputs.input;
    const value = incoming === undefined ? this.config(node).value : incoming;
    return { output: value };
  }

  override settleMemory(node: GraphNode, _portId: string, value: unknown): void {
    node.config.data_value = value as never;
  }

  // ── Build time ────────────────────────────────────────────────────────────

  override graphAuthorNote(): string {
    return `config.data_value is what it remembers between runs.`;
  }

  override whatRuns(): WhatRuns {
    return this.engineRuns('Hands on what arrives this round, or else what it kept; what arrives is kept for the next round.');
  }

  /** The format contract every neighbour is then generated against. */
  override generation(): Generation {
    return {
      kind: 'data_format', fields: DATA_FIELDS,
      guard: 'Please describe the data format first.',
      success: '✅ Data format generated!',
    };
  }
}
