"""
Code execution engine.
Runs Python or JavaScript code in a subprocess with a timeout.
The code module must expose a `run(inputs: dict) -> dict` function.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import subprocess
import tempfile
import textwrap
from typing import Any, Dict, List, Optional

from app.services import code_env

logger = logging.getLogger(__name__)

# Code snippets generated by AI and plot/data transforms often need more than
# a few seconds on slower machines; keep an env override but use a safer
# default to avoid premature timeouts in normal workflows.
EXECUTION_TIMEOUT = int(os.getenv("CODE_EXEC_TIMEOUT", "180"))

# Env vars a child interpreter needs to start up correctly, but nothing else -
# in particular no API keys or other secrets from the backend's environment.
_SUBPROCESS_ENV_ALLOWLIST = {
    "PATH", "PATHEXT", "SYSTEMROOT", "SYSTEMDRIVE", "WINDIR", "COMSPEC",
    "TEMP", "TMP", "HOME", "USERPROFILE", "LANG", "LC_ALL",
}


def _sandboxed_env() -> Dict[str, str]:
    """Minimal environment for a code-node subprocess: no secrets inherited."""
    return {k: v for k, v in os.environ.items() if k.upper() in _SUBPROCESS_ENV_ALLOWLIST}


async def _run_in_subprocess(cmd: list[str], inputs: Dict[str, Any], label: str) -> Dict[str, Any]:
    """Run `cmd` (interpreter + script path already appended) with JSON inputs as argv, JSON output on stdout.

    Dispatches a blocking `subprocess.run` to a worker thread rather than using
    `asyncio.create_subprocess_exec`: uvicorn's `--reload` mode sets `use_subprocess=True`,
    which forces a plain `SelectorEventLoop` on Windows, and that loop raises
    `NotImplementedError` for asyncio subprocesses (only `ProactorEventLoop` supports
    them there). `subprocess.run` works under any event loop.
    """
    # Popen rather than subprocess.run, so a cancelled run can kill the child.
    # `asyncio.to_thread` cannot be interrupted: cancelling the await returns
    # control immediately but leaves the worker thread -- and the process it is
    # waiting on -- running to completion. Stopping a graph would then free the
    # UI while the work carried on unseen, which is the opposite of what Stop is
    # for. Holding the Popen lets the cancellation path actually end it.
    holder: Dict[str, subprocess.Popen] = {}

    def _blocking_run() -> subprocess.CompletedProcess:
        process = subprocess.Popen(
            [*cmd, json.dumps(inputs)],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=_sandboxed_env(),
        )
        holder["process"] = process
        try:
            stdout, stderr = process.communicate(timeout=EXECUTION_TIMEOUT)
        except subprocess.TimeoutExpired:
            process.kill()
            process.communicate()
            raise
        return subprocess.CompletedProcess(process.args, process.returncode, stdout, stderr)

    try:
        try:
            completed = await asyncio.to_thread(_blocking_run)
        except subprocess.TimeoutExpired:
            raise TimeoutError(f"{label} execution timed out after {EXECUTION_TIMEOUT}s")
        except asyncio.CancelledError:
            process = holder.get("process")
            if process is not None and process.poll() is None:
                process.kill()
            raise

        if completed.returncode != 0:
            # errors="replace": a failing interpreter's message is in the OS
            # locale's encoding, not necessarily UTF-8, and a decode error here
            # would mask the actual reason the node failed.
            raise RuntimeError(completed.stderr.decode(errors="replace").strip())

        raw = completed.stdout.decode(errors="replace").strip()
        return json.loads(raw) if raw else {}
    finally:
        os.unlink(cmd[-1])


async def execute_python(
    code: str, inputs: Dict[str, Any], requirements: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """
    Execute Python code with the given inputs.
    The code must define a `run(inputs)` function that returns a dict.

    *requirements* are the packages the node declared. They are checked before
    the snippet runs, so a missing one is a sentence naming it rather than an
    ImportError traceback out of a subprocess -- and nothing is installed here:
    see code_env for why that is an explicit action.
    """
    absent = code_env.missing(requirements or [])
    if absent:
        # Pointing at Install would be a dead end when this build is running on
        # the interpreter it ships: that one has no pip, so the honest next step
        # is installing a real Python rather than pressing a button that cannot work.
        remedy = (
            code_env.EMBEDDED_ONLY_MESSAGE
            if not code_env.describe()["can_install"]
            else "Use Install in the node's editor, or run "
                 "`python main.py --install-requirements` for a deployed bundle."
        )
        raise RuntimeError(
            "This code node needs " + ", ".join(absent) + ", which "
            + ("is" if len(absent) == 1 else "are")
            + " not installed in the code-node environment "
            + f"({code_env.env_dir()}). {remedy}"
        )
    wrapper = textwrap.dedent(
        f"""
import json, sys

{code}

_inputs = json.loads(sys.argv[1])
_outputs = run(_inputs)
print(json.dumps(_outputs))
"""
    )
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".py", delete=False, encoding="utf-8"
    ) as f:
        f.write(wrapper)
        tmp_path = f.name

    return await _run_in_subprocess([code_env.interpreter(), tmp_path], inputs, "Code")


async def execute_javascript(code: str, inputs: Dict[str, Any]) -> Dict[str, Any]:
    """
    Execute JavaScript code with the given inputs via Node.js.
    The code must define a `run(inputs)` function that returns a plain object.
    """
    wrapper = textwrap.dedent(
        f"""
{code}

const _inputs = JSON.parse(process.argv[2]);
const _outputs = run(_inputs);
console.log(JSON.stringify(_outputs));
"""
    )
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".js", delete=False, encoding="utf-8"
    ) as f:
        f.write(wrapper)
        tmp_path = f.name

    return await _run_in_subprocess(["node", tmp_path], inputs, "JavaScript")


async def execute_code(
    code: str, language: str, inputs: Dict[str, Any],
    requirements: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """Dispatch to the correct language executor."""
    lang = language.lower()
    if lang in ("python", "py"):
        return await execute_python(code, inputs, requirements)
    if lang in ("javascript", "js", "node"):
        return await execute_javascript(code, inputs)
    raise ValueError(f"Unsupported code language: {language}")
