"""
Code execution engine.

Runs an authored JavaScript body in a subprocess with a timeout. The body must
expose `run(inputs)` returning a plain object.

A subprocess rather than an evaluator in-process: a body that loops forever,
exits, or prints costs a process rather than the request. The environment it
gets is an allowlist, so nothing from the backend's own environment -- least of
all an API key -- is visible to code a model wrote.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import subprocess
import tempfile
import textwrap
from typing import Any, Dict

logger = logging.getLogger(__name__)

# Code snippets generated by AI and plot/data transforms often need more than
# a few seconds on slower machines; keep an env override but use a safer
# default to avoid premature timeouts in normal workflows.
EXECUTION_TIMEOUT = int(os.getenv("CODE_EXEC_TIMEOUT", "180"))

# Env vars a child interpreter needs to start up correctly, but nothing else -
# in particular no API keys or other secrets from the backend's environment.
_SUBPROCESS_ENV_ALLOWLIST = {
    "PATH", "PATHEXT", "SYSTEMROOT", "SYSTEMDRIVE", "WINDIR", "COMSPEC",
    "TEMP", "TMP", "HOME", "USERPROFILE", "LANG", "LC_ALL",
}


def _sandboxed_env() -> Dict[str, str]:
    """Minimal environment for a code-node subprocess: no secrets inherited."""
    return {k: v for k, v in os.environ.items() if k.upper() in _SUBPROCESS_ENV_ALLOWLIST}


async def _run_in_subprocess(cmd: list[str], inputs: Dict[str, Any], label: str) -> Dict[str, Any]:
    """Run `cmd` (interpreter + script path already appended) with JSON inputs as argv, JSON output on stdout.

    Dispatches a blocking `subprocess.run` to a worker thread rather than using
    `asyncio.create_subprocess_exec`: uvicorn's `--reload` mode sets `use_subprocess=True`,
    which forces a plain `SelectorEventLoop` on Windows, and that loop raises
    `NotImplementedError` for asyncio subprocesses (only `ProactorEventLoop` supports
    them there). `subprocess.run` works under any event loop.
    """
    # Popen rather than subprocess.run, so a cancelled run can kill the child.
    # `asyncio.to_thread` cannot be interrupted: cancelling the await returns
    # control immediately but leaves the worker thread -- and the process it is
    # waiting on -- running to completion. Stopping a graph would then free the
    # UI while the work carried on unseen, which is the opposite of what Stop is
    # for. Holding the Popen lets the cancellation path actually end it.
    holder: Dict[str, subprocess.Popen] = {}

    def _blocking_run() -> subprocess.CompletedProcess:
        process = subprocess.Popen(
            [*cmd, json.dumps(inputs)],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=_sandboxed_env(),
        )
        holder["process"] = process
        try:
            stdout, stderr = process.communicate(timeout=EXECUTION_TIMEOUT)
        except subprocess.TimeoutExpired:
            process.kill()
            process.communicate()
            raise
        return subprocess.CompletedProcess(process.args, process.returncode, stdout, stderr)

    try:
        try:
            completed = await asyncio.to_thread(_blocking_run)
        except subprocess.TimeoutExpired:
            raise TimeoutError(f"{label} execution timed out after {EXECUTION_TIMEOUT}s")
        except asyncio.CancelledError:
            process = holder.get("process")
            if process is not None and process.poll() is None:
                process.kill()
            raise

        if completed.returncode != 0:
            # errors="replace": a failing interpreter's message is in the OS
            # locale's encoding, not necessarily UTF-8, and a decode error here
            # would mask the actual reason the node failed.
            raise RuntimeError(completed.stderr.decode(errors="replace").strip())

        raw = completed.stdout.decode(errors="replace").strip()
        return json.loads(raw) if raw else {}
    finally:
        os.unlink(cmd[-1])


async def execute_javascript(code: str, inputs: Dict[str, Any]) -> Dict[str, Any]:
    """
    Execute JavaScript code with the given inputs via Node.js.
    The code must define a `run(inputs)` function returning a plain object.

    The call is awaited, which matters more than it looks: a model writes
    `async function run` as soon as the description mentions a file or a timer,
    and an un-awaited promise serialises to `{}`. Awaiting a plain value is that
    value, so an ordinary body sees no difference.
    """
    wrapper = textwrap.dedent(
        f"""
{code}

const _inputs = JSON.parse(process.argv[2]);
const _outputs = await run(_inputs);
console.log(JSON.stringify(_outputs));
"""
    )
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".mjs", delete=False, encoding="utf-8"
    ) as f:
        f.write(wrapper)
        tmp_path = f.name

    return await _run_in_subprocess(["node", tmp_path], inputs, "JavaScript")


async def execute_code(code: str, inputs: Dict[str, Any]) -> Dict[str, Any]:
    """Run an authored body. Kept as the name every caller already uses."""
    return await execute_javascript(code, inputs)
