"""
Deployment service.

Assembles a deploy bundle that ships the ACTUAL runtime -- `app/elements`,
`app/models`, and the portable subset of `app/services` -- copied verbatim,
plus the user's `graph.json` and a thin `main.py` (the exact source of
`graph-runner/run.py`). There is no per-node codegen: a deployed graph runs
the same `execute_graph()` as the live editor/CLI, so the two can never
diverge. See AGENTS.md's "Object-oriented element contract" section.
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Dict

from app.elements.base import DeployNeeds
from app.elements.registry import NODE_ELEMENTS
from app.models.graph import Graph

# Root of the actual `app` package this module lives in -- what gets vendored
# into the bundle's app/ folder verbatim (never regenerated/rewritten).
_APP_ROOT = Path(__file__).resolve().parent.parent
# Repo root: only consulted at *build* time to locate graph-runner/run.py to
# embed as main.py; the emitted bundle has no dependency on this layout.
_REPO_ROOT = _APP_ROOT.parent.parent

# Only these app/services/*.py modules are portable (no FastAPI/HTTP-framework
# dependency) and are what graph_executor.py's import chain actually needs;
# routers/, main.py, and this module itself are server-only and never vendored.
_PORTABLE_SERVICE_MODULES = [
    "__init__.py",
    "ai_service.py",
    "batching.py",
    "code_executor.py",
    "file_service.py",
    "graph_executor.py",
]


def _iter_py_files(root: Path):
    """Yield every .py file under *root*, skipping __pycache__ directories."""
    for path in sorted(root.rglob("*.py")):
        if "__pycache__" not in path.parts:
            yield path


def _vendor_app_files() -> Dict[str, str]:
    """
    {bundle-relative path: file content} for every real source file the live
    engine needs: the whole `elements/` tree, `models/graph.py`, and the
    portable `services/*.py` modules above -- copied verbatim, never
    regenerated.
    """
    files: Dict[str, str] = {"app/__init__.py": (_APP_ROOT / "__init__.py").read_text(encoding="utf-8")}

    for path in _iter_py_files(_APP_ROOT / "elements"):
        rel = path.relative_to(_APP_ROOT)
        files[f"app/{rel.as_posix()}"] = path.read_text(encoding="utf-8")

    for name in ("__init__.py", "graph.py"):
        files[f"app/models/{name}"] = (_APP_ROOT / "models" / name).read_text(encoding="utf-8")

    for name in _PORTABLE_SERVICE_MODULES:
        files[f"app/services/{name}"] = (_APP_ROOT / "services" / name).read_text(encoding="utf-8")

    return files


def _requirements_txt(graph: Graph) -> str:
    """
    pip requirements for the bundle: pydantic always (app.models.graph), httpx
    only when the graph actually needs it -- aggregated via each element's
    `deploy_needs`, the same per-element contract `get_runtime_requirements`
    dispatches through, so this never has to branch on node.node_type itself.
    """
    needs = DeployNeeds()
    for node in graph.nodes:
        element = NODE_ELEMENTS.get(node.node_type)
        if element is not None:
            needs = needs | element.deploy_needs(node)
    lines = ["pydantic==2.13.4"]
    if needs.ai:
        lines.append("httpx==0.28.1")
    return "\n".join(lines) + "\n"


def _main_py() -> str:
    """
    The bundle's entrypoint: the exact source of graph-runner/run.py, verbatim.
    That file already documents itself as safe to vendor in as main.py -- its
    dev-only sys.path shim for a sibling `backend/` directory is a no-op once
    copied alongside a bundle's own `app/` instead.
    """
    return (_REPO_ROOT / "graph-runner" / "run.py").read_text(encoding="utf-8")


def _dockerfile() -> str:
    return textwrap.dedent(
        """\
        FROM python:3.11-slim
        WORKDIR /app
        COPY requirements.txt .
        RUN pip install --no-cache-dir -r requirements.txt
        COPY app/ ./app/
        COPY graph.json .
        COPY main.py .
        CMD ["python", "main.py"]
        """
    )


def _readme(graph: Graph) -> str:
    return textwrap.dedent(
        f"""\
        # {graph.metadata.name} — deployment bundle

        Self-contained runner generated by AI-Graph. `app/` is the real AI-Graph
        execution engine (elements + services + models), vendored verbatim -- this
        bundle runs the exact same code as the editor, not a regenerated equivalent.

        ## Run directly with Python
            python -m venv .venv
            . .venv/bin/activate          # Windows: .venv\\Scripts\\activate
            pip install -r requirements.txt
            python main.py graph.json

        ## Run with Docker Compose
            docker compose up --build

        Set AI-provider credentials via environment variables as needed:
        `OLLAMA_BASE_URL`, `OPENAI_API_KEY`, `ANTHROPIC_API_KEY`, `LMSTUDIO_BASE_URL`.
        """
    )


def generate_docker_compose(graph: Graph, image_tag: str = "ai-graph-runner:latest") -> str:
    """Return a docker-compose.yml string for running the vendored bundle."""
    name = graph.metadata.name.lower().replace(" ", "-")

    return textwrap.dedent(
        f"""\
        version: "3.9"

        services:
          {name}-runner:
            build: .
            image: {image_tag}
            environment:
              - OLLAMA_BASE_URL=${{OLLAMA_BASE_URL:-http://ollama:11434}}
              - OPENAI_API_KEY=${{OPENAI_API_KEY:-}}
              - ANTHROPIC_API_KEY=${{ANTHROPIC_API_KEY:-}}
            volumes:
              - ./data:/data

          ollama:
            image: ollama/ollama:latest
            ports:
              - "11434:11434"
            volumes:
              - ollama_data:/root/.ollama

        volumes:
          ollama_data:
        """
    )


def generate_deployment_bundle(graph: Graph) -> Dict[str, str]:
    """
    Return {bundle-relative path: content} for a full, ready-to-run deployment
    bundle:
      - app/**             – the real execution engine, vendored verbatim
      - graph.json         – the graph definition itself
      - main.py            – graph-runner/run.py, verbatim
      - requirements.txt   – pip deps (pydantic always, httpx if the graph uses AI)
      - Dockerfile / docker-compose.yml / README.md – optional run helpers
    Unlike the old codegen approach, the graph definition IS needed at runtime
    (main.py loads graph.json), since there is no more per-graph baked script.
    """
    bundle = _vendor_app_files()
    bundle["graph.json"] = graph.model_dump_json(indent=2)
    bundle["main.py"] = _main_py()
    bundle["requirements.txt"] = _requirements_txt(graph)
    bundle["Dockerfile"] = _dockerfile()
    bundle["docker-compose.yml"] = generate_docker_compose(graph)
    bundle["README.md"] = _readme(graph)
    return bundle
