"""
Deployment service – generates Docker Compose stacks and standalone runner
scripts from a Graph definition so the graph can be deployed and executed
outside the editor.
"""

from __future__ import annotations

import json
import textwrap
from typing import Optional

from app.models.graph import Graph


def generate_docker_compose(graph: Graph, image_tag: str = "ai-graph-runner:latest") -> str:
    """Return a docker-compose.yml string for running the graph."""
    graph_json = graph.model_dump_json(indent=2)
    escaped = graph_json.replace("'", "'\"'\"'")  # shell-safe single quotes
    name = graph.metadata.name.lower().replace(" ", "-")

    compose = textwrap.dedent(
        f"""\
        version: "3.9"

        services:
          {name}-runner:
            image: {image_tag}
            environment:
              - OLLAMA_BASE_URL=${{OLLAMA_BASE_URL:-http://ollama:11434}}
              - OPENAI_API_KEY=${{OPENAI_API_KEY:-}}
              - ANTHROPIC_API_KEY=${{ANTHROPIC_API_KEY:-}}
            volumes:
              - ./data:/data
            command: >
              python /app/graph_runner/run.py /data/graph.json

          ollama:
            image: ollama/ollama:latest
            ports:
              - "11434:11434"
            volumes:
              - ollama_data:/root/.ollama

        volumes:
          ollama_data:
        """
    )
    return compose


def generate_runner_script(graph: Graph) -> str:
    """Return a standalone Python runner script for the given graph."""
    graph_json = graph.model_dump_json(indent=2)
    script = textwrap.dedent(
        f'''\
        #!/usr/bin/env python3
        """
        Auto-generated runner for graph: {graph.metadata.name}
        Generated by AI-Graph deployment tool.
        """
        import asyncio
        import json
        import sys
        from pathlib import Path

        # Allow running from the repo root
        sys.path.insert(0, str(Path(__file__).parent.parent))

        from app.models.graph import Graph
        from app.services.graph_executor import (
            apply_runtime_values,
            execute_graph,
            get_runtime_requirements,
            get_text_output_windows,
        )

        GRAPH_JSON = {repr(graph_json)}


        async def main() -> None:
            graph = Graph.model_validate_json(GRAPH_JSON)

            # Prompt interactively for any values the graph needs
            resolved = {{}}
            for req in get_runtime_requirements(graph):
                if req.kind == "text":
                    prompt_label = f"Text for '{{req.label}}'"
                else:
                    verb = "Read" if req.direction == "input" else "Write"
                    prompt_label = f"{{verb}} {{req.kind}} for '{{req.label}}'"
                default = req.current_value
                suffix = f" [{{default}}]" if default else ""
                answer = input(f"{{prompt_label}}{{suffix}}: ").strip()
                resolved[req.node_id] = answer or default
            apply_runtime_values(graph, resolved)

            result = await execute_graph(graph)
            print(json.dumps(result.model_dump(), indent=2, default=str))

            for window in get_text_output_windows(graph, result):
                border = "=" * 60
                print(f"\n{{border}}\n📄 TEXT OUTPUT: {{window['label']}}\n{{border}}")
                print(window["content"])
                print(border)

            return result


        if __name__ == "__main__":
            asyncio.run(main())
        '''
    )
    return script


def generate_deployment_bundle(graph: Graph) -> dict[str, str]:
    """
    Return a dict of {filename: content} for a full deployment bundle:
      - graph.json      – the graph DSL
      - docker-compose.yml
      - run_graph.py    – standalone runner
    """
    return {
        "graph.json": graph.model_dump_json(indent=2),
        "docker-compose.yml": generate_docker_compose(graph),
        "run_graph.py": generate_runner_script(graph),
    }
