import { describe, it, expect, vi, beforeEach } from 'vitest';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import type { GenerateRequest } from '@/api/client';
import type { ExecutionResult, GraphNode, GuiWidget } from '@/graph';
import { NODE_KINDS } from '@/document/nodeKinds';
import { syncGuiNodePorts } from '@/document/guiWidgets';
import { WIDGET_BUILDERS } from '@/elements/registry';
import { useGraphStore } from '@/store/graphStore';

// What ✨ would send, caught instead of sent.
const sent: GenerateRequest[] = [];
vi.mock('@/api/client', async (original) => ({
  ...(await original<typeof import('@/api/client')>()),
  call: vi.fn(async (_route: string, body: GenerateRequest) => {
    sent.push(body);
    return { result: 'function run(inputs) { return inputs; }', explanation: '', calls: [], probe: { status: 'skipped', attempts: 0, error: '', missing_outputs: [], output_preview: '' } };
  }),
}));

const { blockFacts } = await import('./blockFacts');
const { useGraphSweep } = await import('./useGraphSweep');

const rows = { ...WIDGET_BUILDERS.table.create('Rows'), id: 'rows' } as GuiWidget;

function maker(): GraphNode {
  const node = NODE_KINDS.code.create('maker');
  return {
    ...node, label: 'Rows maker',
    outputs: [{ id: 'rows', name: 'rows', kind: 'output', data_type: 'any', multi: false, required: false, description: 'one object per city' }],
    config: { ...node.config, code: 'function run() { return { rows: [{ city: "Oslo" }] }; }' },
  };
}

function page(widget: GuiWidget): GraphNode {
  return syncGuiNodePorts({ ...NODE_KINDS.gui.create('page'), label: 'Page', config: { ...NODE_KINDS.gui.create('page').config, gui_widgets: [widget] } });
}

const wire = { id: 'e1', source: 'maker', target: 'page', sourceHandle: 'rows', targetHandle: 'rows_in' };

describe('what ✨ is told about a block', () => {
  it('says what feeds the block, and what that node hands on', () => {
    // The bug: a block's ✨ carried only its own request and the scheme, so a
    // transform was written against nothing before the graph had run.
    const facts = blockFacts('page', rows, [maker(), page(rows)], [wire], null, 'night');
    expect(facts.graphContext).toContain('What arrives at this block -- its "value" -- comes from "Rows maker" (port "rows")');
    expect(facts.graphContext).toContain('one object per city');
    expect(facts.graphContext).toContain('a DARK page');
  });

  it('says where the sample came from: the example, else the last run', () => {
    // The bug: no origin was sent, and the engine called any sample "the last run".
    const example = { ...rows, example: '{ "value": [{ "city": "Bergen" }] }' };
    expect(blockFacts('page', example, [], [], null, 'night')).toMatchObject({
      sampleInputs: { value: [{ city: 'Bergen' }] }, sampleOrigin: 'the example in step 1',
    });
    const ran = { node_results: [{ node_id: 'page', inputs: { rows_in: [{ city: 'Oslo' }] } }] } as unknown as ExecutionResult;
    expect(blockFacts('page', rows, [], [], ran, 'night')).toMatchObject({
      sampleInputs: { value: [{ city: 'Oslo' }] }, sampleOrigin: 'the last run',
    });
    expect(blockFacts('page', rows, [], [], null, 'night').sampleInputs).toBeUndefined();
  });

  it('takes in an example file attached before, only while there is no example', () => {
    const attached = { ...rows, example_file: 'data/rows.json' };
    expect(blockFacts('page', attached, [], [], null, 'night').exampleFile).toBe('data/rows.json');
    expect(blockFacts('page', { ...attached, example: '{"value": 1}' }, [], [], null, 'night').exampleFile).toBeUndefined();
  });
});

describe('a block, generated by the graph sweep', () => {
  beforeEach(() => { sent.length = 0; });

  async function sweepOnce(widget: GuiWidget): Promise<GenerateRequest> {
    useGraphStore.getState().loadGraph({
      metadata: { name: 'T', version: '1.0.0', description: '', author: '', tags: [], ai_defaults: { provider: 'default', model: '' }, gui_scheme: 'paper' },
      nodes: [maker(), page({ ...widget, code_prompt: 'One row per city.' })],
      edges: [{ id: 'e1', source_node_id: 'maker', source_port_id: 'rows', target_node_id: 'page', target_port_id: 'rows_in' }],
    } as never);
    let sweep: ReturnType<typeof useGraphSweep> | undefined;
    renderToStaticMarkup(createElement(() => { sweep = useGraphSweep(); return null; }));
    await sweep!.run();
    const asked = sent.find((request) => request.element === 'table');
    expect(asked).toBeDefined();
    return asked!;
  }

  it('is told what its own ✨ button tells it: the scheme, what feeds it, and where the sample came from', async () => {
    // The bug: the sweep sent no scheme and no origin, while its comment said
    // "exactly as its own ✨ button would".
    const asked = await sweepOnce({ ...rows, example: '{ "value": [{ "city": "Bergen" }] }' });
    const button = blockFacts('page', { ...rows, example: '{ "value": [{ "city": "Bergen" }] }' }, [maker(), page(rows)], [wire], null, 'paper');
    expect(asked.context).toContain(button.graphContext!);
    expect(asked.context).toContain('a LIGHT page');
    expect(asked.sample_inputs).toEqual({ value: [{ city: 'Bergen' }] });
    expect(asked.sample_origin).toBe('the example in step 1');
  });
});
