// What an element does, as an object rather than as three field names.
//
// Every element that does anything at all does it the same way: someone writes
// a prompt, an AI turns that prompt into a body, and the body is what runs. A
// code node, an AI node, a file selector and a chart transform are four
// instances of that one sentence, and they differed only in which config keys
// happened to hold the two halves — `code`/`code_prompt` here,
// `selector_code`/`selector_prompt` there, `system_prompt`/the node's own
// description somewhere else.
//
// That difference was expressed as strings: an element returned the *names* of
// its fields and the caller reached into an untyped bag to find them. Two costs
// followed, and both are gone now. `selectFiles` took the element itself plus
// `subject: unknown` and cast it `as never` internally, because the body it
// wanted to run lived behind a generic it could not name. And the same idea was
// declared three times — once here, once in the editor, once in Python — with a
// different field list each time.
//
// So the body becomes a thing. An element hands out a `Logic`; a caller runs
// it. Nobody names a config key, and nobody needs the element to run the body
// it was given.

import type { CodeRunner } from './element.ts';

/**
 * What the body *is*, which decides who executes it.
 *
 * `code` runs in the sandbox. `prompt` is sent to a model as the system half of
 * a request. `spec` is neither: a data node's format contract is written by a
 * person, generated by an AI and read by the *neighbours'* generation prompts,
 * but nothing ever executes it. Naming that third case is what stops it from
 * looking like a body someone forgot to wire up.
 */
export type LogicKind = 'code' | 'prompt' | 'spec';

/** Where a logic keeps its two halves inside an element's stored config. */
export interface LogicFields {
  /** The config key holding the body. */
  body: string;
  /** The config key holding the request that produced it. */
  prompt: string;
  /** The config key holding the file name, when the body may live in a file. */
  file?: string;
  /** The request lives on the node itself (its description), not in config. */
  promptOnSubject?: boolean;
}

/**
 * One element's authored half: the request, the body, and how to run it.
 *
 * Constructed by the element from its own config, so the field names above
 * appear once — in the element that owns them — instead of travelling to every
 * caller that wants the body.
 */
export class Logic {
  /** What the body is, and so who executes it. */
  readonly kind: LogicKind;
  /** The natural-language request that produced `body`. */
  readonly prompt: string;
  /** What runs, or what is sent. Empty means "not written yet". */
  readonly body: string;
  /** Which config keys these came from, for the editor and the file layer. */
  readonly fields: LogicFields;
  /** The file this body is kept in beside the graph; empty means "in the JSON". */
  readonly file: string;
  /** For the editor's sentence: "keep <what> in a file". */
  readonly what: string;

  // Fields declared and assigned rather than written as constructor parameter
  // properties: the engine has to survive Node's type stripping, and a
  // parameter property is one of the few TypeScript spellings that emits code
  // rather than only removing types. `strippable.test.ts` holds every file here
  // to that.
  constructor(
    kind: LogicKind,
    prompt: string,
    body: string,
    fields: LogicFields,
    file = '',
    what = 'this body',
  ) {
    this.kind = kind;
    this.prompt = prompt;
    this.body = body;
    this.fields = fields;
    this.file = file;
    this.what = what;
  }

  /**
   * The extension a file holding this body should have.
   *
   * Derived rather than declared: real code gets `.js` and an editor's language
   * support with it, prose gets `.md` because prose in a `.js` is a syntax
   * error. This used to be a field every element filled in, which is how one of
   * them came to say `.py` long after the last Python body was gone.
   */
  get extension(): string {
    return this.kind === 'code' ? '.js' : '.md';
  }

  /** Whether anything was actually written. */
  get isEmpty(): boolean {
    return !this.body.trim();
  }

  /**
   * Run the body over *inputs*.
   *
   * Only meaningful for `code`; a prompt is sent by the element that owns the
   * model call, and a spec is never run at all. An empty body passes the inputs
   * through — the sane default, which used to mean three different things in
   * three elements: one called the sandbox anyway and failed with a reference
   * error out of a subprocess, one guarded first, one passed through.
   *
   * No failure policy here on purpose: whether a broken body costs the node or
   * only the block that shows it is a property of the *element*, not of the
   * body, so the element wraps this (see `Element.runSnippet`).
   */
  async run(inputs: Record<string, unknown>, code: CodeRunner): Promise<Record<string, unknown>> {
    if (this.isEmpty) return inputs;
    return code.run(this.body, inputs);
  }
}

/** Read a logic straight off a subject's config, given where its halves live. */
export function logicFrom(
  subject: { config: Record<string, unknown>; description?: string },
  kind: LogicKind,
  fields: LogicFields,
  what: string,
): Logic {
  const prompt = fields.promptOnSubject
    ? String(subject.description ?? '')
    : String(subject.config[fields.prompt] ?? '');
  return new Logic(
    kind,
    prompt,
    String(subject.config[fields.body] ?? ''),
    fields,
    fields.file ? String(subject.config[fields.file] ?? '') : '',
    what,
  );
}
